-- ============================================
-- MIGRACIÓN: Sistema de Caché ArcGIS con Sincronización (PostgreSQL)
-- Versión: 001
-- Descripción: Tablas optimizadas para almacenar registros y fotos de ArcGIS
-- ============================================

-- Función para actualizar timestamp
CREATE OR REPLACE FUNCTION update_timestamp()
RETURNS TRIGGER AS $$
BEGIN
  NEW.local_updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Tabla principal para registros de ArcGIS
CREATE TABLE IF NOT EXISTS arcgis_records (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  
  -- Identificadores únicos de ArcGIS
  objectid BIGINT NOT NULL,
  globalid TEXT NOT NULL UNIQUE,
  
  -- Códigos de identificación
  codigo_accion TEXT,
  otro_ca TEXT,
  
  -- Información geográfica y temporal
  fecha TEXT,
  norte DOUBLE PRECISION,
  este DOUBLE PRECISION,
  zona TEXT,
  datum TEXT,
  altitud DOUBLE PRECISION,
  
  -- Información del componente
  componente TEXT,
  tipo_componente TEXT,
  detalle_componente TEXT,
  numero_punto TEXT,
  
  -- Clasificación
  tipo_de_reporte TEXT,
  subcomponente TEXT,
  
  -- Personal
  nombre_supervisor TEXT,
  
  -- Observaciones
  descripcion TEXT,
  hallazgos TEXT,
  profundidad DOUBLE PRECISION,
  
  -- Descripciones de fotografías
  descripcion_f01 TEXT,
  descripcion_f02 TEXT,
  descripcion_f03 TEXT,
  descripcion_f04 TEXT,
  descripcion_f05 TEXT,
  descripcion_f06 TEXT,
  descripcion_f07 TEXT,
  descripcion_f08 TEXT,
  descripcion_f09 TEXT,
  descripcion_f10 TEXT,
  
  -- Metadatos de ArcGIS
  creation_date TEXT,
  creator TEXT,
  edit_date TEXT,
  editor TEXT,
  
  -- JSON completo para campos adicionales no mapeados
  raw_json TEXT NOT NULL,
  
  -- Campos de sincronización local
  synced_at TIMESTAMPTZ DEFAULT NOW(),
  local_created_at TIMESTAMPTZ DEFAULT NOW(),
  local_updated_at TIMESTAMPTZ DEFAULT NOW(),
  is_deleted INTEGER DEFAULT 0, -- Soft delete para detectar eliminaciones
  
  -- Checksum para detección rápida de cambios
  checksum TEXT
);

-- Índices para búsquedas rápidas
CREATE INDEX IF NOT EXISTS idx_arcgis_globalid ON arcgis_records(globalid);
CREATE INDEX IF NOT EXISTS idx_arcgis_objectid ON arcgis_records(objectid);
CREATE INDEX IF NOT EXISTS idx_arcgis_codigo_accion ON arcgis_records(codigo_accion);
CREATE INDEX IF NOT EXISTS idx_arcgis_otro_ca ON arcgis_records(otro_ca);
CREATE INDEX IF NOT EXISTS idx_arcgis_supervisor ON arcgis_records(nombre_supervisor);
CREATE INDEX IF NOT EXISTS idx_arcgis_tipo_reporte ON arcgis_records(tipo_de_reporte);
CREATE INDEX IF NOT EXISTS idx_arcgis_subcomponente ON arcgis_records(subcomponente);
CREATE INDEX IF NOT EXISTS idx_arcgis_fecha ON arcgis_records(fecha);
CREATE INDEX IF NOT EXISTS idx_arcgis_edit_date ON arcgis_records(edit_date);
CREATE INDEX IF NOT EXISTS idx_arcgis_is_deleted ON arcgis_records(is_deleted);
CREATE INDEX IF NOT EXISTS idx_arcgis_synced_at ON arcgis_records(synced_at);

-- Índice compuesto para búsquedas por código
CREATE INDEX IF NOT EXISTS idx_arcgis_codigo_composite 
  ON arcgis_records(codigo_accion, otro_ca, is_deleted);

-- Trigger para actualizar local_updated_at
DROP TRIGGER IF EXISTS update_arcgis_records_timestamp ON arcgis_records;
CREATE TRIGGER update_arcgis_records_timestamp 
BEFORE UPDATE ON arcgis_records
FOR EACH ROW
WHEN (NEW.is_deleted = 0)
EXECUTE FUNCTION update_timestamp();

-- ============================================
-- Tabla para fotografías de ArcGIS
-- ============================================
CREATE TABLE IF NOT EXISTS arcgis_photos (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  
  -- Relación con registro
  record_id BIGINT NOT NULL,
  record_globalid TEXT NOT NULL,
  
  -- Información de ArcGIS
  attachment_id BIGINT NOT NULL,
  objectid BIGINT NOT NULL,
  
  -- Información del archivo
  filename TEXT NOT NULL,
  content_type TEXT,
  file_size BIGINT,
  
  -- Almacenamiento local
  local_path TEXT NOT NULL UNIQUE, -- Ruta relativa desde uploads/
  local_size BIGINT,
  
  -- Metadata opcional
  keywords TEXT,
  exif_data TEXT, -- JSON con datos EXIF si existen
  
  -- Campos de sincronización
  synced_at TIMESTAMPTZ DEFAULT NOW(),
  local_created_at TIMESTAMPTZ DEFAULT NOW(),
  local_updated_at TIMESTAMPTZ DEFAULT NOW(),
  is_deleted INTEGER DEFAULT 0,
  
  -- Checksum para verificar integridad
  checksum TEXT,
  
  -- Foreign key
  FOREIGN KEY (record_id) REFERENCES arcgis_records(id) ON DELETE CASCADE
);

-- Índices para fotografías
CREATE INDEX IF NOT EXISTS idx_arcgis_photos_record_id ON arcgis_photos(record_id);
CREATE INDEX IF NOT EXISTS idx_arcgis_photos_globalid ON arcgis_photos(record_globalid);
CREATE INDEX IF NOT EXISTS idx_arcgis_photos_attachment_id ON arcgis_photos(attachment_id);
CREATE INDEX IF NOT EXISTS idx_arcgis_photos_objectid ON arcgis_photos(objectid);
CREATE INDEX IF NOT EXISTS idx_arcgis_photos_filename ON arcgis_photos(filename);
CREATE INDEX IF NOT EXISTS idx_arcgis_photos_is_deleted ON arcgis_photos(is_deleted);
CREATE INDEX IF NOT EXISTS idx_arcgis_photos_synced_at ON arcgis_photos(synced_at);

-- Índice compuesto para evitar duplicados
CREATE UNIQUE INDEX IF NOT EXISTS idx_arcgis_photos_unique 
  ON arcgis_photos(objectid, attachment_id, is_deleted);

-- Trigger para actualizar local_updated_at
DROP TRIGGER IF EXISTS update_arcgis_photos_timestamp ON arcgis_photos;
CREATE TRIGGER update_arcgis_photos_timestamp 
BEFORE UPDATE ON arcgis_photos
FOR EACH ROW
WHEN (NEW.is_deleted = 0)
EXECUTE FUNCTION update_timestamp();

-- ============================================
-- Tabla de códigos de acción (para búsquedas rápidas)
-- ============================================
CREATE TABLE IF NOT EXISTS arcgis_codigos (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  codigo TEXT NOT NULL UNIQUE,
  tipo TEXT NOT NULL, -- 'codigo_accion' o 'otro_ca'
  record_count INTEGER DEFAULT 0,
  last_sync_at TEXT,
  synced_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_arcgis_codigos_codigo ON arcgis_codigos(codigo);
CREATE INDEX IF NOT EXISTS idx_arcgis_codigos_tipo ON arcgis_codigos(tipo);
CREATE INDEX IF NOT EXISTS idx_arcgis_codigos_last_sync ON arcgis_codigos(last_sync_at);

-- ============================================
-- Tabla de log de sincronización
-- ============================================
CREATE TABLE IF NOT EXISTS arcgis_sync_log (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  codigo TEXT NOT NULL,
  operation TEXT NOT NULL, -- 'full', 'incremental', 'force'
  
  -- Estadísticas
  records_before INTEGER DEFAULT 0,
  records_after INTEGER DEFAULT 0,
  records_inserted INTEGER DEFAULT 0,
  records_updated INTEGER DEFAULT 0,
  records_deleted INTEGER DEFAULT 0,
  
  photos_before INTEGER DEFAULT 0,
  photos_after INTEGER DEFAULT 0,
  photos_inserted INTEGER DEFAULT 0,
  photos_deleted INTEGER DEFAULT 0,
  
  -- Tiempos
  started_at TIMESTAMPTZ DEFAULT NOW(),
  completed_at TIMESTAMPTZ,
  duration_ms INTEGER,
  
  -- Estado
  status TEXT NOT NULL DEFAULT 'pending', -- 'pending', 'running', 'completed', 'error'
  error_message TEXT
);

CREATE INDEX IF NOT EXISTS idx_arcgis_sync_log_codigo ON arcgis_sync_log(codigo);
CREATE INDEX IF NOT EXISTS idx_arcgis_sync_log_started ON arcgis_sync_log(started_at DESC);
CREATE INDEX IF NOT EXISTS idx_arcgis_sync_log_status ON arcgis_sync_log(status);

-- ============================================
-- Vista para registros activos (no eliminados)
-- ============================================
CREATE OR REPLACE VIEW arcgis_records_active AS
SELECT * FROM arcgis_records WHERE is_deleted = 0;

-- ============================================
-- Vista para fotografías activas
-- ============================================
CREATE OR REPLACE VIEW arcgis_photos_active AS
SELECT * FROM arcgis_photos WHERE is_deleted = 0;

-- ============================================
-- Vista con estadísticas por código
-- ============================================
CREATE OR REPLACE VIEW arcgis_stats_by_codigo AS
SELECT 
  COALESCE(codigo_accion, otro_ca) as codigo,
  CASE 
    WHEN codigo_accion IS NOT NULL THEN 'codigo_accion'
    ELSE 'otro_ca'
  END as tipo,
  COUNT(*) as total_registros,
  COUNT(CASE WHEN is_deleted = 0 THEN 1 END) as registros_activos,
  MAX(edit_date) as ultima_edicion,
  MAX(synced_at) as ultima_sincronizacion
FROM arcgis_records
WHERE codigo_accion IS NOT NULL OR otro_ca IS NOT NULL
GROUP BY codigo, tipo;
